[build]
    command = "npm run prod"
    publish = "build_production"
    environment = { PHP_VERSION = "8.1" }

[functions]
        node_bundler = "esbuild"

[[redirects]]
    from = "/blog"
    to = "https://digitalproductbasics.com/?utm_campaign=mksq&utm_source=markhamsquare.com&utm_medium=nav"
    status = 301